---
title: "Re-processing of hand2(+)-subpopulations"
author: "Helena L. Crowell"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    code_folding: hide
    df_print: paged
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, cache.lazy = FALSE)
```

### Load packages

```{r load-libs, message = FALSE, warning = FALSE}
library(cowplot)
library(ggplot2)
library(dplyr)
library(magrittr)
library(purrr)
library(readxl)
library(reshape2)
library(scater)
library(Seurat)
library(tree)
```

### Load data

```{r load-data}
so <- readRDS(file.path("output", "so_anno.rds"))
source(file.path("code", "utils.R"))
```

# Re-processing of hand2(+)-subset

```{r grouping, fig.width = 6, fig.height = 3}
hand2 <- grep("hand2", rownames(so), value = TRUE)
hand2_expr <- GetAssayData(so, "data", "RNA")[hand2, ]

data.frame(x = hand2_expr) %>% 
  ggplot(aes(x)) + labs(x = "hand2 expression") +
  geom_histogram(bins = 100, color = "white") +
  geom_vline(xintercept = 2, col = "red") +
  scale_y_sqrt() + theme_linedraw()
```

```{r Seurat-wrapper}
# wrapper to run default Seurat analysis
.Seurat <- function(so) {
  # normalize, scale, find HVGs
  so <- NormalizeData(so)
  so <- FindVariableFeatures(so)
  so <- ScaleData(so, vars.to.regress = c("total", "subsets_mt_percent"))
  # dimension reductions
  so <- RunPCA(so, features = VariableFeatures(so))
  so <- RunTSNE(so, reduction = "pca", dims = 1:10, seed.use = 42)
  so <- RunUMAP(so, reduction = "pca", dims = 1:10, seed.use = 42)
  # clustering
  so <- FindNeighbors(so, reduction = "pca", dims = 1:10)
  so <- FindClusters(so, verbose = FALSE, random.seed = 42)
  return(so)
}
```

```{r run-Seurat, warning = FALSE, message = FALSE}
# nb. and % of cells in ea. group
length(cs <- colnames(so)[hand2_expr > 2])

# run Seurat on hand2(+)-subset
sub <- .Seurat(subset(so, cells = cs))

# compare previous & subset clusterings
t(table(droplevels(Idents(sub)), 
    droplevels(Idents(so)[cs])))
```

## Annotation

```{r anno}
anno <- read_xlsx(file.path("data", "cluster_anno_hand2.xlsx"))
anno <- setNames(anno$label, anno$cluster_id)
anno <- anno[as.character(Idents(sub))]
Idents(sub) <- factor(anno)
```

# Marker genes

## Canonical markers

```{r}
mgs <- read_xlsx(file.path("data", "marker_genes_hand2.xlsx"))
ss <- strsplit(mgs$markers, ", ", fixed = TRUE)
s <- sub[["RNA"]]@meta.features$symbol
m <- match(unlist(ss), s, nomatch = 0)
gs <- rownames(sub)[m]
```

### Dotplot

```{r dp1, message = FALSE, fig.width = 12, fig.height = 4}
(p <- .dotplot(sub, gs))
```

## `Seurat` markers

```{r mgs2, results = "asis"}
# identify cluster-markers
mgs <- FindAllMarkers(sub,
    only.pos = TRUE, logfc.threshold = 0.25, 
    min.pct = 0.25, verbose = FALSE)
top <- filter(mgs, p_val_adj < 0.05) %>% 
    group_by(cluster) %>% 
    top_n(12, avg_logFC) %>% 
    ungroup
```

### Dotplot

```{r dp2, message = FALSE, fig.width = 16, fig.height = 4}
.dotplot(sub, unique(top$gene))
```

### Violins {.tabset}

```{r violins, results = "asis", fig.width = 14, fig.asp = 0.5}
for (id in levels(Idents(sub))) {
    cat("#### ", id, "\n")
    fs <- filter(top, cluster == id)$gene
    ps <- VlnPlot(sub, features = fs, combine = FALSE)
    ps <- lapply(ps, function(p) p + labs(x = NULL, y = NULL) + 
            theme_minimal() + theme(legend.position = "none", 
                plot.title = element_text(size = 10, hjust = 0.5)))
    print(plot_grid(plotlist = ps, ncol = 4))
    cat("\n\n")
}
```

# Dimension reduction

## Colored by cluster ID

```{r umap-id, results = "asis", fig.width = 12, fig.height = 4}
ps <- lapply(c("pca", "umap", "tsne"), 
    function(dr) DimPlot(sub, reduction = dr))
lgd <- get_legend(ps[[1]])
ps <- lapply(ps, "+", theme(aspect.ratio = 1, legend.position = "none"))
plot_grid(plotlist = c(ps, list(lgd)),
    nrow = 1, rel_widths = c(1, 1, 1, 0.5))
```

## Colored by cluster-marker expression {.tabset}

```{r umap-expr, results = "asis", fig.width = 12, fig.asp = 2/3}
for (id in levels(Idents(sub))) {
    cat("### ", id, "\n")
    fs <- dplyr::filter(top, cluster == id)$gene
    ps <- FeaturePlot(sub, features = fs, combine = FALSE) %>% 
        lapply(function(p) p + theme_void() + theme(
            aspect.ratio = 1, legend.position = "none", 
            panel.background = element_rect(fill = NA, size = 0.4),
            panel.grid.major = element_line(size = 0.2, color = "lightgrey"),
            plot.title = element_text(size = 10, hjust = 0.5)))
    print(plot_grid(plotlist = ps, ncol = 4))
    cat("\n\n")
}
```

# Classification tree {.tabset}

```{r tree, results = "asis", fig.width = 10, fig.height = 8}
y <- GetAssayData(sub)
y <- y[VariableFeatures(sub), ]
mat <- as.matrix(y)
ss <- strsplit(rownames(mat), ":")
s1 <- sapply(ss, .subset, 1)
s2 <- sapply(ss, function(u) paste(u[-1], collapse = ":"))
s2[s2 == ""] <- s1[s2 == ""]
rownames(mat) <- s2
df <- data.frame(y = Idents(sub), as.data.frame(t(mat)))
fit <- tree(y ~ ., data = df)
plot(fit); text(fit)
```
