---
title: "Bloodvessel subset"
author: "Helena L. Crowell"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    code_folding: hide
    df_print: paged
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, cache.lazy = FALSE)
```

### Load packages

```{r load-libs, message = FALSE, warning = FALSE}
library(cowplot)
library(dplyr)
library(ggplot2)
library(Matrix)
library(reshape2)
library(Seurat)
library(SingleCellExperiment)
```

### Load & prep. data

```{r load-data}
source(file.path("code", "utils.R"))

so <- readRDS(file.path("output", "so_anno.rds"))
sce <- readRDS(file.path("output", "sce_anno.rds"))

bv_clusts <- c(
    "anterior vasculature",
    "hemangioblasts and kidney_1", 
    "hemangioblasts and kidney_2")
```

# Re-processing

```{r prep, warning = FALSE, fig.width = 5, fig.height = 3}
# subset bloodvessel clusters
so <- so[, so$cluster_id %in% bv_clusts]
table(droplevels(so$cluster_id))

# re-run dimension reduction
so <- RunPCA(so, 
    features = VariableFeatures(so), 
    verbose = FALSE, seed.use = 42)
ElbowPlot(so)
so <- RunUMAP(so, 
    reduction = "pca", dims = seq_len(15), 
    verbose = FALSE, seed = 42)

# construct SCE
rd <- rowData(sce)[rownames(so), ]
sub <- as.SingleCellExperiment(so)
rowData(sub) <- rd

# extract relevant features
fs <- c(
    "cdx4", "lbx2", "nkx2.7", "tbx20", "etv2", "tal1", "lmo2", 
    "gata2a", "gata5", "fli1a", "pax2a", "tmem88a", "tmem88b")
m <- match(fs, rowData(sub)$symbol)
gs <- rownames(sub)[m]
names(fs) <- gs

# construct data.frame of expression, 
# cell metadata, and dimension reductions
cd <- colData(sub)
dr <- do.call("cbind", reducedDims(sub))
es <- as.matrix(t(logcounts(sub)[gs, ]))
df <- data.frame(cd, dr, es, check.names = FALSE)
df <- df[sample(nrow(df), nrow(df)), ] # randomize cell ordering
df <- melt(df, id.vars = c(colnames(cd), colnames(dr)),
    variable.name = "gene", value.name = "expression")
```

# Dimension reduction

## Colored by cluster ID

```{r dr-id, fig.width = 8, fig.height = 3}
thm <- list(geom_point(),
    scale_color_manual(values = cluster_pal),
    guides(color = guide_legend(override.aes = list(size = 3))),
    theme_bw(), theme(aspect.ratio = 1, panel.grid.minor = element_blank()))
p1 <- ggplot(df, aes(x = PC_1, y = PC_2, col = cluster_id)) + thm
p2 <- ggplot(df, aes(x = UMAP_1, y = UMAP_2, col = cluster_id)) + thm
plot_grid(nrow = 1, rel_widths = c(3,3,2),
    p1 + theme(legend.position = "none"),
    p2 + theme(legend.position = "none"), 
    get_legend(p1))
```

```{r echo = FALSE}
p <- ggplot(df, aes(x = UMAP_1, y = UMAP_2, col = cluster_id)) + 
    geom_point(size = 0.2, alpha = 0.8) +
     scale_color_manual(values = cluster_pal) +
    guides(color = guide_legend(NULL, ncol = 1, 
        override.aes = list(alpha = 1, size = 2))) +
    labs(x = "UMAP dim. 1", y = "UMAP dim. 2") +
    theme_minimal(base_size = 8) + theme(aspect.ratio = 1,
        panel.grid = element_blank(),
        axis.text = element_blank(),
        legend.key.height = unit(2, "mm"),
        legend.position = "bottom",
        panel.background = element_rect(fill = NA, size = 0.4, color = "black"))
ggsave(file.path("figures", "bv-umap_cluster_id.pdf"), p,
    width = 5, height = 6, unit = "cm",
    dpi = 300, useDingbats = FALSE)
```

## Colored by exression

```{r dr-expr, fig.width = 10, fig.height = 6}
ps <- lapply(gs, function(g)
    ggplot(filter(df, gene == g), 
        aes(x = UMAP_1, y = UMAP_2, col = expression)) +
        geom_point(size = 0.8, alpha = 0.8) + 
        scale_color_viridis_c(NULL, option = "C") +
        ggtitle(fs[g]) + theme_void() + 
        theme(legend.key.width = unit(2, "mm"), 
            plot.title = element_text(hjust = 0.5)))
plot_grid(plotlist = ps, ncol = 5)
```

```{r echo = FALSE, message = FALSE, results = "hide"}
lgd <- get_legend(ps[[1]] +  theme_void(base_size = 6) + 
    theme(legend.key.width = unit(3, "mm"),
        legend.key.height = unit(3, "mm")) + 
    scale_color_viridis_c("scaled\nexpression", 
        option = "C", limits = c(0,1)))
ps <- lapply(ps, function(p) {
    p$layers[[1]]$aes_params$size <- 0
    p + theme_void(base_size = 6) + theme(
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(size = 0.2, color = "black"))
})
pdf(file.path("figures", "bv-umap_expression.pdf"), 
    width = 15/2.54, height = 5/2.54)
plot_grid(plotlist = c(list(lgd), ps), ncol = 7)
dev.off()
```

## Tmem88a/b

```{r umap-tmem, fig.width = 12, fig.height = 6}
tmem <- grep("tmem88", rowData(sce)$symbol)
ps <- lapply(rownames(sce)[tmem], function(g) {
    df <- data.frame(reducedDim(sce, "UMAP"),
        gene = g, expr = logcounts(sce)[g, ])
    ggplot(df, aes(x = UMAP_1, y = UMAP_2, col = expr)) +
        geom_point(size = 0.8, alpha = 0.8) + 
        scale_color_viridis_c(NULL, option = "C") +
        ggtitle(rowData(sce[g, ])$symbol) + theme_void() + 
        theme(legend.key.width = unit(2, "mm"), 
            plot.title = element_text(hjust = 0.5))
})
plot_grid(plotlist = ps, ncol = 2)
```

```{r echo = FALSE, message = FALSE, results = "hide"}
lgd <- get_legend(ps[[1]] +  theme_void(base_size = 6) + 
    theme(legend.key.width = unit(3, "mm"),
        legend.key.height = unit(3, "mm")) + 
    scale_color_viridis_c("scaled\nexpression", 
        option = "C", limits = c(0,1)))
ps <- lapply(ps, function(p) {
    p$layers[[1]]$aes_params$size <- 0
    p + theme_void(base_size = 6) + theme(
        aspect.ratio = 1, legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(size = 0.2, color = "black"))
})
pdf(file.path("figures", "bv-umap_tmem88.pdf"), 
    width = 8/2.54, height = 4/2.54)
plot_grid(plotlist = c(ps, list(lgd)), 
    ncol = 3, rel_widths = c(2,2,1))
dev.off()
```

# Dotplot

```{r results = "hide"}
# get hierarchical orderings
pdf("foo")
hm <- heatmap(ms <- data.frame(cluster_id = sub$cluster_id, 
    t(GetAssayData(so[gs, ], "scale.data")), check.names = FALSE) %>% 
    group_by(cluster_id) %>% summarize_all(mean) %>% 
    data.frame(row.names = 1, check.names = FALSE) %>% as.matrix)
unlink("foo")
row_o <- rownames(ms)[hm$rowInd]
col_o <- gs[hm$colInd]
```

```{r dotplot, warning = FALSE, message = FALSE, fig.width = 8, fig.height = 3}
(p <- DotPlot(so, features = gs) + 
    scale_y_discrete(limits = row_o, expand = c(0, 0.5)) +
    scale_x_discrete(limits = col_o, expand = c(0, 0.5),
        labels = rowData(sub)[col_o, "symbol"]) +
    scale_color_gradientn(limits = c(-1.2,1.2), breaks = seq(-1,1,1),
        colors = c("darkcyan", "grey95", "tomato", "darkred")) +
    scale_size_continuous(labels = formatC(seq(0,1,0.25), 2, format = "f")) +
    guides(size = guide_legend("expression\nfrequency"),
        color = guide_colorbar("scaled mean\nexpression", order = 1)) +
        coord_equal() + theme_void() + theme(
            plot.margin = margin(0,1,0,0, "cm"),
            legend.position = "top",
            axis.text.x = element_text(angle = 45, hjust = 1),
            axis.text.y = element_text()))
```

```{r echo = FALSE, message = FALSE}
p <- p + scale_size_continuous(
    breaks = seq(0, 100, 25), range = c(0, 3), 
    labels = formatC(seq(0,1,0.25), 2, format = "f")) + 
    theme_minimal(base_size = 6) + theme(
        plot.margin = margin(0,4,0,0, "mm"),
        legend.key.size = unit(2, "mm"),
        legend.position = "bottom",
        legend.justification = c(-10,0),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_text(color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(file.path("figures", "bv-dotplot.pdf"),
    width = 9, height = 3, units = "cm", useDingbats = FALSE)
```

# Violins

```{r}
.violins <- function(df) {
    ggplot(df, aes(x = cluster_id, y = expression, fill = cluster_id)) +
        geom_violin(width = 1, alpha = 0.6, size = 0.2) +
        geom_boxplot(width = 0.2, size = 0.1, alpha = 1,
            col = "black", outlier.color = NA, show.legend = FALSE) +
        scale_color_manual(NULL, values = cluster_pal) +
        scale_fill_manual(NULL, values = cluster_pal) +
        guides(fill = guide_legend(override.aes = list(alpha = 1))) +
        scale_y_continuous(limits = c(0, 4.5), breaks = seq(0, 4, 2)) +
        theme_minimal() + ggtitle(fs[df$gene[1]]) + theme(
            legend.key.size = unit(4, "mm"),
            panel.grid.minor = element_blank(),
            plot.title = element_text(hjust = 0.5),
            axis.text.x = element_blank(),
            axis.title.x = element_blank())
}
```

```{r violins, fig.width = 8, fig.height = 4}
ps <- lapply(setdiff(gs, grep("tmem", gs, value = TRUE)), 
    function(g) .violins(filter(df, gene == g)))
plot_grid(ncol = 4, plotlist = c(
    lapply(ps, "+", theme(legend.position = "none")), 
    list(get_legend(ps[[1]]))))
```

```{r echo = FALSE, results = "hide"}
ps <- lapply(ps,  function(p) 
    p + theme_minimal(base_size = 6) + theme(  
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(color = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(size = 0.1, color = "grey")))

lgd <- get_legend(ps[[1]] + theme(legend.key.size = unit(2, "mm")))
ps <- lapply(ps, "+", theme(legend.position = "none"))
fn <- file.path("figures", "bv-violins.pdf")
pdf(fn, width = 15/2.54, height = 6/2.54)
plot_grid(plotlist = c(ps, list(lgd)), ncol = 4)
dev.off()
```

## Tmem88a/b only

```{r}
cd <- colData(sce)
dr <- do.call("cbind", reducedDims(sce))
es <- as.matrix(t(logcounts(sce)[gs, ]))
df <- data.frame(cd, dr, es, check.names = FALSE)
df <- df[sample(nrow(df), nrow(df)), ] # randomize cell ordering
df <- melt(df, id.vars = c(colnames(cd), colnames(dr)),
    variable.name = "gene", value.name = "expression")
df <- filter(df, gene == rownames(sce)[tmem[1]])
ex_fq <- group_by(df, cluster_id) %>% 
    summarize(detected = mean(expression > 0))
(p <- .violins(df) +
    geom_point(data = ex_fq, 
        aes(cluster_id, 4, size = detected)) +  
    scale_y_continuous(limits = c(0, 4)) +
    scale_size_continuous(
        "expression\nfrequency", range = c(0, 5),
        labels = formatC(seq(0,1,0.25), 2, format = "f")) +
    guides(fill = FALSE) + theme(
        axis.text.y = element_text(color = "black"),
        axis.text.x = element_text(color = "black", 
            angle = 30, size = 8, vjust = 1, hjust = 1)))
```

```{r echo = FALSE, results = "hide"}
fn <- file.path("figures", "bv-tmem88a_violins.pdf")
pdf(fn, width = 15/2.54, height = 8/2.54, useDingbats = FALSE); p; dev.off()
```

