---
title: "Contents"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

- [Preprocessing](0-preprocessing.html):
    - Retrieval of gene symbols from Ensembl
    - Calculation of QC metrics, including mitochondrial content 
    - Removal of outliers using `scater`
    - Computation of log-transformed library-size normalized counts
    - Removal of low-quality plate 4
    
- [Clustering](1-clustering.html):
    - `Seurat` clustering using a sequence of resolutions
    - Number of clusters by resolution
    - `clustree` to investigate stability of clusters
    - t-SNE and UMAP dimension reductions 
    - Dot plot of canonical marker genes
    - DGEA using `Seurat`'s `FindAllMarkers`
    - Dot plot & heatmap of DE genes
    
- [Annotation](2-annotation.html):
    - manual annotation of 15 `Seurat` clusters into 6 major subpopulations
    - UMAP colored by manual annotation ID
    - UMAPs, dot plots & heatmaps of canonical markers & hox genes
    - DE analysis on super-cluster of merged hand2+ clusters
    - Dot plot of hand2+ super-cluster markers